# Generated by Django 4.2.3 on 2023-09-08 13:54

import app_seguro.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='help_text', max_length=20, verbose_name='Estado Civil')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Localidad')),
                ('departamentos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='app_seguro.departamento')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Por ejemplo: Ministerio, Municipalidad', max_length=150, unique=True, verbose_name='Organismo')),
                ('domicilio', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, help_text='Correo Electrónico', max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Frecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('pregunta', models.CharField(max_length=254)),
                ('respuesta', models.CharField(max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Saf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Denoninación S.A.F.')),
                ('nros', models.CharField(help_text='En caso de ser varios, separelos por coma', max_length=100, verbose_name='Nros. de S.A.F.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'S.A.F.',
                'verbose_name_plural': 'S.A.F.',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipodoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True, verbose_name='Tipo de Doc.')),
                ('abreviado', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Doc.',
                'verbose_name_plural': 'Tipo de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombres')),
                ('nro', models.CharField(help_text='Sin puntos, ni guiones', max_length=12, unique=True, validators=[app_seguro.models.validate_integer], verbose_name='Número')),
                ('vive', models.BooleanField(default=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], default='F', max_length=1)),
                ('cuil', models.CharField(help_text='Sin guiones', max_length=11, unique=True, verbose_name='CUIL')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(help_text='correo Electrónico', max_length=254, unique=True)),
                ('domicilio', models.CharField(max_length=80)),
                ('cp', models.CharField(default='4700', help_text='Ejemplo 4700', max_length=10, verbose_name='Código Postal')),
                ('discapacidad', models.BooleanField(default=False)),
                ('situacion', models.CharField(choices=[('Activo', 'ACTIVO'), ('Jubilado', 'JUBILADO')], default='ACTIVO', max_length=8, verbose_name='Situación')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.departamento', verbose_name='Departamento')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.estadocivil', verbose_name='Estado Civil')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.localidad')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.organismo')),
                ('safs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.saf')),
                ('tipodoc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_seguro.tipodoc', verbose_name='Tipo Doc.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Seguro', max_length=100, verbose_name='Seguro')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('legal', models.CharField(max_length=120, verbose_name='Ley/Decreto de Creación')),
                ('activo', models.BooleanField(default=True)),
                ('requisito_ingreso', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Requisitos de Ingreso')),
                ('requisito_cobro', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Requisitos para Cobro')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Requisito')),
                ('tipo', models.CharField(blank=True, choices=[('file', 'Archivo'), ('text', 'Texto'), ('number', 'Número')], max_length=7)),
                ('seguros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.seguro')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo Hijo/a', max_length=20, unique=True, verbose_name='Parentesco')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Oficina')),
                ('domicilio', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, help_text='Correo Electrónico', max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('organismos', models.ForeignKey(help_text='Ministerio, Empresa', on_delete=django.db.models.deletion.PROTECT, to='app_seguro.organismo')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargadorSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nro', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombres')),
                ('nrodoc', models.CharField(default=0, help_text='Sin puntos', max_length=12, unique=True, verbose_name='D.N.I.')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], default='F', max_length=1)),
                ('cuil', models.CharField(help_text='Sin guiones', max_length=11, unique=True, verbose_name='CUIL')),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(help_text='correo Electrónico', max_length=254, unique=True)),
                ('cp', models.CharField(help_text='Ejemplo 4700', max_length=10, verbose_name='Código Postal')),
                ('activo', models.BooleanField(default=False, verbose_name='Puede Cargar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('oficinas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.oficina')),
                ('organismos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.organismo')),
                ('safs', models.ManyToManyField(to='app_seguro.saf', verbose_name='S.A.F.')),
                ('tipodoc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_seguro.tipodoc', verbose_name='Tipo Doc.')),
            ],
            options={
                'verbose_name': 'Cargador de Seguros',
                'verbose_name_plural': 'Cargadores de Seguros',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_created=True, auto_now_add=True)),
                ('created', models.DateField(auto_created=True, auto_now_add=True)),
                ('nro', models.CharField(max_length=8, validators=[app_seguro.models.validate_integer])),
                ('apellido', models.CharField(blank=True, max_length=40, null=True)),
                ('nombres', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=60, null=True)),
                ('barrio', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('seguro_vida', models.BooleanField(default=False, verbose_name='Seguro de Vida Obligatorio')),
                ('seguro_facultativo', models.BooleanField(default=False, verbose_name='Seguro de Vida Facultativo Obligatorio')),
                ('seguro_sepelio', models.BooleanField(default=False, verbose_name='Seguro de Sepelio')),
                ('seguro_conyuge', models.BooleanField(default=False, verbose_name='Seguro de Vida Conyuge')),
                ('subsidio_proteccion_flia', models.BooleanField(default=False, verbose_name='Subsidio de Protección a la Familia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.departamento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.localidad')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parentescos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_seguro.parentesco', verbose_name='Relación de Parentesco')),
                ('tipodoc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_seguro.tipodoc', verbose_name='Tipo Doc.')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_seguro.titular')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ['-id'],
            },
        ),
    ]
