# Generated by Django 4.2.3 on 2023-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titular',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Titular', 'verbose_name_plural': 'Titulares'},
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Estado Civil'),
        ),
    ]
