# Generated by Django 4.2.3 on 2023-09-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0002_alter_titular_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titular',
            old_name='dpto',
            new_name='departamento',
        ),
    ]
