# Generated by Django 4.2.3 on 2023-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0003_rename_dpto_titular_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='email',
            field=models.EmailField(blank=True, help_text='correo Electrónico', max_length=254, null=True),
        ),
    ]
