# Generated by Django 4.2.3 on 2023-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0004_alter_titular_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('is_activo', models.BooleanField(default=True, verbose_name='En Actividad')),
                ('correo', models.EmailField(max_length=250)),
                ('mensaje', models.TextField(max_length=250)),
                ('lugar_trabajo', models.CharField(max_length=100, verbose_name='Lugar de Trabajo o Trabajo')),
                ('is_respondido', models.BooleanField(default=False)),
            ],
        ),
    ]
