# Generated by Django 4.2.3 on 2023-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0005_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='titular',
            name='edito',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
