# Generated by Django 4.2.3 on 2023-10-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0007_remove_contacto_is_activo_alter_beneficiario_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='is_respondido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='lugar_trabajo',
        ),
    ]
