# Generated by Django 4.2.3 on 2023-10-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguro', '0008_remove_contacto_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo',
            new_name='email',
        ),
    ]
